// ============================================================
// 1. (Categories)
// ============================================================
export const categories = [
  {
    id: 1,
    name: "مكسرات ولوز",
    nameEn: "Nuts & Almonds",
    slug: "nuts-almonds",
    image: "/product-img.png",
  },
  {
    id: 2,
    name: "ألبان ومشتقاتها",
    nameEn: "Dairy Products",
    slug: "dairy",
    image: "/product-img.png",
  },
  {
    id: 3,
    name: "أجار ومخللات",
    nameEn: "Pickles & Achars",
    slug: "pickles-achar",
    image: "/product-img.png",
  },
  {
    id: 4,
    name: "صوصات وتوابل",
    nameEn: "Sauces & Spices",
    slug: "sauces-spices",
    image: "/product-img.png",
  },
  {
    id: 5,
    name: "فواكه موسمية",
    nameEn: "Seasonal Fruits",
    slug: "seasonal-fruits",
    image: "/product-img.png",
  },
  {
    id: 6,
    name: "منتجات تقليدية",
    nameEn: "Traditional Products",
    slug: "traditional",
    image: "/product-img.png",
  },
  {
    id: 7,
    name: "هدايا وباقات",
    nameEn: "Gifts & Baskets",
    slug: "gifts-baskets",
    image: "/product-img.png",
  },
  {
    id: 8,
    name: "عصائر ومربيات",
    nameEn: "Juices & Jams",
    slug: "juices-jams",
    image: "/product-img.png",
  },
];

// ============================================================
// 2. (Subcategories)
// ============================================================
export const subcategories = [
  // (mainCategoryId: 1) => Nuts & Almonds
  {
    id: 101,
    name: "لوز أصفر",
    nameEn: "Yellow Almonds",
    slug: "yellow-almonds",
    mainCategoryId: 1,
  },
  {
    id: 102,
    name: "لوز بيذام مكس",
    nameEn: "Almond Beidam Mix",
    slug: "almond-beidam",
    mainCategoryId: 1,
  },
  {
    id: 103,
    name: "لوز مقطع حامض سبايسي",
    nameEn: "Spicy Sour Almonds",
    slug: "spicy-sour-almonds",
    mainCategoryId: 1,
  },
  {
    id: 104,
    name: "لوز مقطع حامض عادي",
    nameEn: "Regular Sour Almonds",
    slug: "regular-sour-almonds",
    mainCategoryId: 1,
  },
  {
    id: 105,
    name: "آجار اللوز سبيشال",
    nameEn: "Almond Pickle Special",
    slug: "almond-pickle",
    mainCategoryId: 1,
  },

  // (mainCategoryId: 2) => Dairy Products
  {
    id: 201,
    name: "لبن بقر",
    nameEn: "Cow Milk",
    slug: "cow-milk",
    mainCategoryId: 2,
  },
  {
    id: 202,
    name: "لبن بقر بالحلبة",
    nameEn: "Cow Milk with Fenugreek",
    slug: "milk-fenugreek",
    mainCategoryId: 2,
  },
  {
    id: 203,
    name: "زبدة بقر",
    nameEn: "Cow Butter",
    slug: "cow-butter",
    mainCategoryId: 2,
  },
  {
    id: 204,
    name: "جبن بقري",
    nameEn: "Cow Cheese",
    slug: "cow-cheese",
    mainCategoryId: 2,
  },
  { id: 205, name: "جامي", nameEn: "Jami", slug: "jami", mainCategoryId: 2 },
  { id: 206, name: "يقط", nameEn: "Yaqut", slug: "yaqut", mainCategoryId: 2 },

  // (mainCategoryId: 3) => Pickles & Achars
  {
    id: 301,
    name: "آجار ليمون",
    nameEn: "Lemon Pickle",
    slug: "lemon-pickle",
    mainCategoryId: 3,
  },
  {
    id: 302,
    name: "آجار البمبر",
    nameEn: "Bamber Pickle",
    slug: "bamber-pickle",
    mainCategoryId: 3,
  },
  {
    id: 303,
    name: "آجار همبا سبيشال",
    nameEn: "Himba Special Pickle",
    slug: "himba-special",
    mainCategoryId: 3,
  },
  {
    id: 304,
    name: "آجار همبا عادي",
    nameEn: "Himba Regular Pickle",
    slug: "himba-regular",
    mainCategoryId: 3,
  },
  {
    id: 305,
    name: "آجار همبا حامض حلو",
    nameEn: "Himba Sour-Sweet Pickle",
    slug: "himba-sour-sweet",
    mainCategoryId: 3,
  },

  // (mainCategoryId: 4) => Sauces & Spices
  {
    id: 401,
    name: "شطة حارة",
    nameEn: "Hot Chili Sauce",
    slug: "hot-chili",
    mainCategoryId: 4,
  },
  {
    id: 402,
    name: "صوص همبا سبيشال",
    nameEn: "Himba Special Sauce",
    slug: "himba-special-sauce",
    mainCategoryId: 4,
  },
  {
    id: 403,
    name: "صوص همبا عادي",
    nameEn: "Himba Regular Sauce",
    slug: "himba-regular-sauce",
    mainCategoryId: 4,
  },

  // (mainCategoryId: 5) => Seasonal Fruits
  { id: 501, name: "حيب", nameEn: "Haib", slug: "haib", mainCategoryId: 5 },
  {
    id: 502,
    name: "لوز أصفر",
    nameEn: "Yellow Almonds",
    slug: "yellow-almonds-fruit",
    mainCategoryId: 5,
  },
  {
    id: 503,
    name: "فرصاد أحمر",
    nameEn: "Red Farsad",
    slug: "red-farsad",
    mainCategoryId: 5,
  },
  {
    id: 504,
    name: "توت بري",
    nameEn: "Wild Berries",
    slug: "wild-berries",
    mainCategoryId: 5,
  },
  {
    id: 505,
    name: "توت سكري",
    nameEn: "Sweet Berries",
    slug: "sweet-berries",
    mainCategoryId: 5,
  },
  {
    id: 506,
    name: "ذرة حلوة",
    nameEn: "Sweet Corn",
    slug: "sweet-corn",
    mainCategoryId: 5,
  },

  // (mainCategoryId: 6) => Traditional Products
  { id: 601, name: "سمن", nameEn: "Ghee", slug: "ghee", mainCategoryId: 6 },
  {
    id: 602,
    name: "جامي",
    nameEn: "Jami",
    slug: "jami-traditional",
    mainCategoryId: 6,
  },
  {
    id: 603,
    name: "لبن بقر",
    nameEn: "Cow Milk",
    slug: "cow-milk-traditional",
    mainCategoryId: 6,
  },
  {
    id: 604,
    name: "يقط",
    nameEn: "Yaqut",
    slug: "yaqut-traditional",
    mainCategoryId: 6,
  },

  // (mainCategoryId: 7) => Gifts & Baskets
  {
    id: 701,
    name: "باقة السلة المميزة",
    nameEn: "Special Basket",
    slug: "special-basket",
    mainCategoryId: 7,
  },
  {
    id: 702,
    name: "بوكس الحيب",
    nameEn: "Haib Box",
    slug: "haib-box",
    mainCategoryId: 7,
  },

  // (mainCategoryId: 8) => Juices & Jams
  {
    id: 801,
    name: "مربى توت صغير",
    nameEn: "Small Mulberry Jam",
    slug: "small-mulberry-jam",
    mainCategoryId: 8,
  },
  {
    id: 802,
    name: "مربى توت كبير",
    nameEn: "Large Mulberry Jam",
    slug: "large-mulberry-jam",
    mainCategoryId: 8,
  },
];

// ============================================================
// 3. (Products) => subcategorySlug
// ============================================================
export const products = [
  {
    id: 1,
    name: "حيـــب",
    nameEn: "Haib Fruit",
    price: 299,
    discountedPrice: 249,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "1 كيلو",
    category: "fruits",
    subcategorySlug: "haib",
    image: "/product-img.png",
    description:
      "هو قلب النخلة 🤍🌴 ويسمى الجمار أو الجذبة في دول أخرى.. فاكهة شتوية ذات قيمة غذائية عالية جدًا وطعم لذيذ وحلو . . بالمختصر شيء فاخر 👌🏽",
  },
  {
    id: 2,
    name: "لوز اصفر (2 كيلو)",
    nameEn: "Yellow Almonds (2kg)",
    price: 270,
    discountedPrice: 240,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "2 كيلو",
    category: "fruits",
    subcategorySlug: "yellow-almonds-fruit",
    image: "/product-img.png",
    description:
      "فاكهة الصيف اللذيذة 😋 حيث يستمتع الصغار والكبار بطعمه ما بين الحلو والحامض 👌🏽",
  },
  {
    id: 3,
    name: "لوز / بيذام مكس (2 كيلو)",
    nameEn: "Almond / Beidam Mix (2kg)",
    price: 270,
    discountedPrice: 240,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "2 كيلو",
    category: "fruits",
    subcategorySlug: "almond-beidam",
    image: "/products/Almond-Beidam-Mix.jpeg",
    description:
      "بلونيه الأحمر والأصفر حائز على لقب فاكهة الصيف اللذيذة 😋 حيث يستمتع الصغار والكبار بطعمه ما بين الحلو والحامض 👌🏽",
  },
  {
    id: 4,
    name: "لوز مقطع حامض سبايسي",
    nameEn: "Spicy Sour Almonds",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "250 جم",
    category: "fruits",
    subcategorySlug: "spicy-sour-almonds",
    image: "/product-img.png",
    description:
      "فاكهة الصيف اللذيذة 😋 جربوها مع الخلطة اللذيذة بالليمون والرمان 🍋‍🟩🌶️",
  },
  {
    id: 5,
    name: "كيلو فرصاد أحمر",
    nameEn: "Red Farsad (1kg)",
    price: 90,
    discountedPrice: 80,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "1 كيلو",
    category: "fruits",
    subcategorySlug: "red-farsad",
    image: "/products/Red-Farsad-(1kg).jpeg",
    description:
      "ضيف موسمي محبوب عند الجميع يحمل معه عبق الماضي ونكهة الطبيعة وبشائر الصيف ❣️☀️",
  },
  {
    id: 6,
    name: "توت بري",
    nameEn: "Wild Berries",
    price: 90,
    discountedPrice: 80,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "1 كيلو",
    category: "fruits",
    subcategorySlug: "wild-berries",
    image: "/products/Wild-Berries.jpeg",
    description:
      "التوت البني أو الباكستاني طعم وحلاوة وقوام متين، من أجود وأشهر أنوع التوت والأكثر طلب في موسمه ✨",
  },
  {
    id: 7,
    name: "كيلو توت سكري",
    nameEn: "Green Sweet Berries (1kg)",
    price: 90,
    discountedPrice: 80,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    countryCode: "uae",
    originEn: "UAE 🇦🇪",
    weight: "1 كيلو",
    category: "fruits",
    subcategorySlug: "sweet-berries",
    image: "/products/Green-Sweet-Berries-(1kg).jpeg",
    description: "يتميز بلونه الأخضر وطعم حلو المذاق كالعسل 🍯",
  },
  {
    id: 8,
    name: "سمــــن",
    nameEn: "Ghee",
    price: 75,
    discountedPrice: 69,
    discountPercent: 8,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "500 جم",
    category: "dairy",
    subcategorySlug: "ghee",
    image: "/product-img.png",
    description: "نكهة مميزة وطعم أصيل وقيمة راسخة في مطبخنا العربي 💫",
  },
  {
    id: 9,
    name: "جامــــي",
    nameEn: "Jami Dessert",
    price: 28,
    discountedPrice: 25,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "250 جم",
    category: "dairy",
    subcategorySlug: "jami",
    image: "/products/Jami.jpeg",
    description:
      "الجامي من الاكلات التراثية الشعبية يستخلص من لبن البقر ويؤكل مع التمر ويضاف له السمن ويتميز بطعمه الطيب👌🏽",
  },
  {
    id: 10,
    name: "لبن بقر",
    nameEn: "Cow Milk",
    price: 35,
    discountedPrice: 30,
    discountPercent: 14,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "1 لتر",
    category: "dairy",
    subcategorySlug: "cow-milk",
    image: "/product-img.png",
    description:
      "يتميز لبن البقر بطعم حامض وقوام أسمك من الحليب.. سهل الهضم، طبيعي وطازج، من المزرعة للبيت🥛",
  },
  {
    id: 11,
    name: "زبدة بقرّ 1 كيلو",
    nameEn: "Cow Butter 1kg",
    price: 180,
    discountedPrice: 150,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "1 كيلو",
    category: "dairy",
    subcategorySlug: "cow-butter",
    image: "/products/Cow-Butter-1kg.jpeg",
    description:
      "اكتشف الطعم الطيب لزبدة البقر المصنوعة من الحليب الطازج النقي.. غنية بالدهون الصحية والفيتامينات والمعادن.. أساسية في كل مطبخ 😉 🧈",
  },
  {
    id: 12,
    name: "يقط",
    nameEn: "Yaqut",
    price: 18,
    discountedPrice: 15,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "250 جم",
    category: "fruits",
    subcategorySlug: "yaqut",
    image: "/products/Yaqut.jpeg",
    description:
      "جزء من تراثنا الشعبي يحمل ذكريات الطفولة 🤍 عبارة عن كرات مجففة من اللبن المحمض الطازج",
  },
  {
    id: 13,
    name: "لبن بقر بالحلبة",
    nameEn: "Cow Milk with Fenugreek",
    price: 35,
    discountedPrice: 30,
    discountPercent: 14,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "1 لتر",
    category: "dairy",
    subcategorySlug: "milk-fenugreek",
    image: "/products/Cow-Milk-Fenugreek.jpeg",
    description:
      "استمتع بنكهة الحلبة اللذيذة المضافة إلى لبن البقر الحامض🐄 .. غنية بالقيمة الغذائية والطعم فاخر من الآخر😋",
  },
  {
    id: 14,
    name: "زبدة بقر نصف كيلو",
    nameEn: "Cow Butter 0.5kg",
    price: 120,
    discountedPrice: 100,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "500 جم",
    category: "dairy",
    subcategorySlug: "cow-butter",
    image: "/products/Cow-Butter-haf.jpeg",
    description:
      "اكتشف الطعم الطيب لزبدة البقر المصنوعة من الحليب الطازج النقي.. غنية بالدهون الصحية والفيتامينات والمعادن.. أساسية في كل مطبخ 😉 🧈",
  },
  {
    id: 15,
    name: "كيلو صبار / حمبل",
    nameEn: "Cactus Fruit (1kg)",
    price: 80,
    discountedPrice: 80,
    discountPercent: 0,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "1 كيلو",
    category: "fruits",
    subcategorySlug: "cactus-fruit-1kg",
    image: "/products/cactus.jpeg",
    description:
      "من فواكه الصيف ذات الشعبية الكبيرة، له مسميات أخرى مثل التين الشوكي. يتميز بمذاقه المميز ✨",
  },
  {
    id: 16,
    name: "آجار البمبر (امبو)",
    nameEn: "Bamber Pickle",
    price: 55,
    discountedPrice: 49,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "500 جم",
    category: "pickles",
    subcategorySlug: "bamber-pickle",
    image: "/product-img.png",
    description: "نكهة أصيلة ومتفردة.. مثالي مع الأكلات الشعبية 😉✨",
  },
  {
    id: 17,
    name: "لوز مقطع حامض عادي",
    nameEn: "Regular Sour Almonds",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "250 جم",
    category: "fruits",
    subcategorySlug: "regular-sour-almonds",
    image: "/product-img.png",
    description: "غير حار",
  },
  {
    id: 18,
    name: "باقة السلة المميزة",
    nameEn: "Special Basket",
    price: 350,
    discountedPrice: 299,
    discountPercent: 15,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "متنوع",
    category: "gifts",
    subcategorySlug: "special-basket",
    image: "/products/Special-Basket.jpeg",
    description:
      "سلة الأصالة 💐 … هي أكثر من هدية، هي لحظات نعيشها مع تراثنا، وطعم ماينسى من أيام الطيبين ⌛️🎁",
  },
  {
    id: 19,
    name: "جبن بقري",
    nameEn: "Cow Cheese",
    price: 45,
    discountedPrice: 39,
    discountPercent: 13,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "500 جم",
    category: "dairy",
    subcategorySlug: "cow-cheese",
    image: "/product-img.png",
    description: "مصنوع من الحليب البقري الطبيعي",
  },
  {
    id: 20,
    name: "شطة حارة",
    nameEn: "Hot Chili Sauce",
    price: 18,
    discountedPrice: 15,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "250 مل",
    category: "sauces",
    subcategorySlug: "hot-chili",
    image: "/products/Hot-Chili-Sauce.jpeg",
    description:
      "أضف النكهة القوية واللمسة النارية لأطباقك مع صلصة الشطة الحارة",
  },
  {
    id: 21,
    name: "صوص همبا سبيشال",
    nameEn: "Himba Special Sauce",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "250 مل",
    category: "sauces",
    subcategorySlug: "himba-special-sauce",
    image: "/product-img.png",
    description: "مزيج لذيذ يجمع بين حلاوة المانجو ولمسة من التوابل الخاصة",
  },
  {
    id: 22,
    name: "صوص همبا عادي",
    nameEn: "Himba Regular Sauce",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "250 مل",
    category: "sauces",
    subcategorySlug: "himba-regular-sauce",
    image: "/product-img.png",
    description:
      "بلونه الأصفر الذهبي وقوامه الناعم، يجمع بين حلاوة المانجو الطبيعية ولمسة خفيفة من الحموضة",
  },
  {
    id: 23,
    name: "آجار اللوز سبيشال (حجم صغير)",
    nameEn: "Almond Pickle Special (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "200 جم",
    category: "pickles",
    subcategorySlug: "almond-pickle",
    image: "/product-img.png",
    description:
      "هذا الآجار المميز الذي لا يمكن تفويته .. مذاق اللوز الاصلي مع البهارات",
  },
  {
    id: 24,
    name: "آجار همبا سبيشال (حجم صغير)",
    nameEn: "Himba Pickle Special (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "200 جم",
    category: "pickles",
    subcategorySlug: "himba-special",
    image: "/products/Himba-Special-Pickle-Small.jpeg",
    description: "ننتقي أجود أنواع الهمبا لنصنع لكم هذا الآجار المميز",
  },
  {
    id: 25,
    name: "آجار همبا عادي (حجم صغير)",
    nameEn: "Himba Pickle Regular (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "200 جم",
    category: "pickles",
    subcategorySlug: "himba-regular",
    image: "/products/Himba-Regular-Pickle-Small.jpeg",
    description:
      "مخلل المانجو التقليدي الذي يأسر الحواس ويضفي لمسة خاصة على موائدكم",
  },
  {
    id: 26,
    name: "آجار ليمون (حجم صغير)",
    nameEn: "Lemon Pickle (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "200 جم",
    category: "pickles",
    subcategorySlug: "lemon-pickle",
    image: "/products/Lemon-Pickle-(small).jpeg",
    description:
      "أضف الحموضة المنعشة لأطباقك مع آجار الليمون ذو النكهة الخلابة",
  },
  {
    id: 27,
    name: "آجار همبا حامض حلو (حجم صغير)",
    nameEn: "Himba Sour-Sweet Pickle (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "200 جم",
    category: "pickles",
    subcategorySlug: "himba-sour-sweet",
    image: "/product-img.png",
    description:
      "استمتع بتجربة فريدة مع الآجار الذي يجمع بين الحموضة المنعشة والحلاوة الخفيفة",
  },
  {
    id: 28,
    name: "بوكس الحيب",
    nameEn: "Haib Box",
    price: 140,
    discountedPrice: 125,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "متنوع",
    category: "fruits",
    subcategorySlug: "haib-box",
    image: "/products/Haib-Box.jpeg",
    description:
      "قلب النخلة 🤍🌴 ويسمى الجمار أو الجذبة في دول أخرى.. فاكهة شتوية ذات قيمة غذائية عالية جدًا وطعم لذيذ وحلو . . بالمختصر شيء فاخر 👌🏽",
  },
  {
    id: 29,
    name: "ذرة راس الخيمة الحلوة",
    nameEn: "Sweet RAK Corn",
    price: 45,
    discountedPrice: 39,
    discountPercent: 13,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "250 جم",
    category: "fruits",
    subcategorySlug: "sweet-corn",
    image: "/products/Sweet-RAK-Corn.jpeg",
    description:
      "من خير بلادنا 🌽 يحبها الصغير و الكبير 🥰 لذيذة و فوائدها عظيمة 😍",
  },
  {
    id: 30,
    name: "مربى توت (غرشة صغيرة)",
    nameEn: "Small Mulberry Jam",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "200 جم",
    category: "jams",
    subcategorySlug: "small-mulberry-jam",
    image: "/product-img.png",
    description: "مربى توت طبيعي بطعم غني ولذيذ 😋 مثالي للفطور والحلويات 👌🏽✨",
  },
  {
    id: 31,
    name: "مربى توت (غرشة كبيرة)",
    nameEn: "Large Mulberry Jam",
    price: 55,
    discountedPrice: 49,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "500 جم",
    category: "jams",
    subcategorySlug: "large-mulberry-jam",
    image: "/product-img.png",
    description: "مربى توت طبيعي بطعم غني ولذيذ 😋 مثالي للفطور والحلويات 👌🏽✨",
  },
  {
    id: 32,
    name: "عصير توت كبير (1.5 لتر)",
    nameEn: "Large Berry Juice (1.5L)",
    price: 45,
    discountedPrice: 45,
    discountPercent: 0,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "1.5 لتر",
    category: "juices",
    subcategorySlug: "large-berry-juice",
    image: "/products/Berry-Juice-large.jpeg",
    description: "عصير توت طبيعي ومنعش 🍇😋 حجم عائلي وطعم يبرد القلب 👌🏽❄️✨",
  },
  {
    id: 33,
    name: "همبا حامض (حدال) 4 كيلو",
    nameEn: "Sour Mango (4kg)",
    price: 70,
    discountedPrice: 70,
    discountPercent: 0,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "4 كيلو",
    category: "fruits",
    subcategorySlug: "sour-mango-4kg",
    image: "/products/Sour-Mango-(4kg).jpeg",
    description:
      "المانجو أو الامبا الحامض أو الحدال، من الثمار المعروفة بطعمها الحامض 😋 تؤكل مع الليمون والملح والفلفل وتستخدم في عمل الآجار",
  },
  {
    id: 34,
    name: "خل الليمون",
    nameEn: "Lemon Vinegar",
    price: 0,
    discountedPrice: 0,
    discountPercent: 0,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    countryCode: "uae",
    weight: "—",
    category: "vinegar",
    subcategorySlug: "lemon-vinegar",
    image: "/products/Lemon-Vinegar.jpeg",
    description:
      "خل ليمون طبيعي بطعم منعش 🍋 مثالي للسلطات والتتبيلات ويضيف نكهة مميزة للأطعمة 👌✨",
  },
];

// ============================================================
// 4. Help function for obtaining subcategory products
// ============================================================
export function getProductsBySubcategorySlug(slug: string) {
  return products.filter((p) => p.subcategorySlug === slug);
}

// 5. Obtaining products from the main classification (using dependent sub-classifications)
export function getProductsByMainCategorySlug(slug: string) {
  // 6. Finding the main classification
  const mainCategory = categories.find((cat) => cat.slug === slug);
  if (!mainCategory) return [];
  // 7. Find all subcategories belonging to this main category
  const subCats = subcategories.filter(
    (sub) => sub.mainCategoryId === mainCategory.id,
  );
  // 8. Obtaining the names of the slugs for the subcategories
  const subSlugs = subCats.map((sub) => sub.slug);
  // 9. Bring products that fall under any of these subcategories
  return products.filter((product) =>
    subSlugs.includes(product.subcategorySlug),
  );
}

// ============================================================
// 10. UAE list (for TapBar)
// ============================================================
export const emirates = [
  { ar: "دبي", en: "Dubai" },
  { ar: "أبو ظبي", en: "Abu Dhabi" },
  { ar: "الشارقة", en: "Sharjah" },
  { ar: "عجمان", en: "Ajman" },
  { ar: "رأس الخيمة", en: "Ras Al Khaimah" },
  { ar: "الفجيرة", en: "Fujairah" },
  { ar: "أم القيوين", en: "Umm Al Quwain" },
];
