// ** categories
export const categories = [
  {
    id: 1,
    name: "فواكه موسمية",
    nameEn: "Seasonal Fruits",
    slug: "seasonal-fruits",
    image: "/categories/seasonal-fruits.jpeg",
  },
  {
    id: 2,
    name: "ألبان ومشتقاتها",
    nameEn: "Dairy Products",
    slug: "dairy",
    image: "/categories/dairy.jpeg",
  },
  {
    id: 3,
    name: "أجارات وصوصات",
    nameEn: "Pickles & Sauces",
    slug: "pickles-sauces",
    image: "/categories/pickles-sauces.jpeg",
  },
  {
    id: 4,
    name: "عصائر",
    nameEn: "Juices",
    slug: "juices",
    image: "/categories/juices.jpeg",
  },
];

// ** products
export const products = [
  {
    id: 1,
    name: "حيـــب",
    nameEn: "Haib Fruit",
    price: 299,
    discountedPrice: 249,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1 كيلو",
    categorySlug: "seasonal-fruits", // Direct link to main category slug
    image: "/products/seasonal-fruits/haib-fruit.jpeg",
    description:
      "هو قلب النخلة 🤍🌴 ويسمى الجمار أو الجذبة في دول أخرى.. فاكهة شتوية ذات قيمة غذائية عالية جدًا وطعم لذيذ وحلو . . بالمختصر شيء فاخر 👌🏽",
  },
  {
    id: 2,
    name: "لوز اصفر (2 كيلو)",
    nameEn: "Yellow Almonds (2kg)",
    price: 270,
    discountedPrice: 240,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "2 كيلو",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Yellow-Almonds-(2kg).jpeg",
    description:
      "فاكهة الصيف اللذيذة 😋 حيث يستمتع الصغار والكبار بطعمه ما بين الحلو والحامض 👌🏽",
  },
  {
    id: 3,
    name: "لوز / بيذام مكس (2 كيلو)",
    nameEn: "Almond / Beidam Mix (2kg)",
    price: 270,
    discountedPrice: 240,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "2 كيلو",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Almond-Beidam-Mix.jpeg",
    description:
      "بلونيه الأحمر والأصفر حائز على لقب فاكهة الصيف اللذيذة 😋 حيث يستمتع الصغار والكبار بطعمه ما بين الحلو والحامض 👌🏽",
  },
  {
    id: 4,
    name: "لوز مقطع حامض سبايسي",
    nameEn: "Spicy Sour Almonds",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "250 جم",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Spicy-Sour-Almonds.jpeg",
    description:
      "فاكهة الصيف اللذيذة 😋 جربوها مع الخلطة اللذيذة بالليمون والرمان 🍋‍🟩🌶️",
  },
  {
    id: 5,
    name: "كيلو فرصاد أحمر",
    nameEn: "Red Farsad (1kg)",
    price: 90,
    discountedPrice: 80,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1 كيلو",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Red-Farsad-(1kg).jpeg",
    description:
      "ضيف موسمي محبوب عند الجميع يحمل معه عبق الماضي ونكهة الطبيعة وبشائر الصيف ❣️☀️",
  },
  {
    id: 6,
    name: "توت بري",
    nameEn: "Wild Berries",
    price: 90,
    discountedPrice: 80,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1 كيلو",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Wild-Berries.jpeg",
    description:
      "التوت البني أو الباكستاني طعم وحلاوة وقوام متين، من أجود وأشهر أنوع التوت والأكثر طلب في موسمه ✨",
  },
  {
    id: 7,
    name: "كيلو توت سكري",
    nameEn: "Green Sweet Berries (1kg)",
    price: 90,
    discountedPrice: 80,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1 كيلو",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Green-Sweet-Berries-(1kg).jpeg",
    description: "يتميز بلونه الأخضر وطعم حلو المذاق كالعسل 🍯",
  },
  {
    id: 8,
    name: "سمن",
    nameEn: "Ghee",
    price: 75,
    discountedPrice: 69,
    discountPercent: 8,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "500 جم",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Ghee.jpeg",
    description: "نكهة مميزة وطعم أصيل وقيمة راسخة في مطبخنا العربي 💫",
  },
  {
    id: 9,
    name: "جامــــي",
    nameEn: "Jami Dessert",
    price: 28,
    discountedPrice: 25,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "250 جم",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Jami.jpeg",
    description:
      "الجامي من الاكلات التراثية الشعبية يستخلص من لبن البقر ويؤكل مع التمر ويضاف له السمن ويتميز بطعمه الطيب👌🏽",
  },
  {
    id: 10,
    name: "لبن بقر",
    nameEn: "Cow Milk",
    price: 35,
    discountedPrice: 30,
    discountPercent: 14,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1 لتر",
    categorySlug: "dairy",
    image: "/products/dairy/Cow-Milk.jpeg",
    description:
      "يتميز لبن البقر بطعم حامض وقوام أسمك من الحليب.. سهل الهضم، طبيعي وطازج، من المزرعة للبيت🥛",
  },
  {
    id: 11,
    name: "زبدة بقرّ 1 كيلو",
    nameEn: "Cow Butter 1kg",
    price: 180,
    discountedPrice: 150,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1 كيلو",
    categorySlug: "dairy",
    image: "/products/dairy/Cow-Butter-1kg.jpeg",
    description:
      "اكتشف الطعم الطيب لزبدة البقر المصنوعة من الحليب الطازج النقي.. غنية بالدهون الصحية والفيتامينات والمعادن.. أساسية في كل مطبخ 😉 🧈",
  },
  {
    id: 12,
    name: "يقط",
    nameEn: "Yaqut",
    price: 18,
    discountedPrice: 15,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "250 جم",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Yaqut.jpeg",
    description:
      "جزء من تراثنا الشعبي يحمل ذكريات الطفولة 🤍 عبارة عن كرات مجففة من اللبن المحمض الطازج",
  },
  {
    id: 13,
    name: "لبن بقر بالحلبة",
    nameEn: "Cow Milk with Fenugreek",
    price: 35,
    discountedPrice: 30,
    discountPercent: 14,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1 لتر",
    categorySlug: "dairy",
    image: "/products/dairy/Cow-Milk-Fenugreek.jpeg",
    description:
      "استمتع بنكهة الحلبة اللذيذة المضافة إلى لبن البقر الحامض🐄 .. غنية بالقيمة الغذائية والطعم فاخر من الآخر😋",
  },
  {
    id: 14,
    name: "زبدة بقر نصف كيلو",
    nameEn: "Cow Butter 0.5kg",
    price: 120,
    discountedPrice: 100,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "500 جم",
    categorySlug: "dairy",
    image: "/products/dairy/Cow-Butter-half.jpeg",
    description:
      "اكتشف الطعم الطيب لزبدة البقر المصنوعة من الحليب الطازج النقي.. غنية بالدهون الصحية والفيتامينات والمعادن.. أساسية في كل مطبخ 😉 🧈",
  },
  {
    id: 15,
    name: "كيلو صبار / حمبل",
    nameEn: "Cactus Fruit (1kg)",
    price: 80,
    discountedPrice: 80,
    discountPercent: 0,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1 كيلو",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/cactus.jpeg",
    description:
      "من فواكه الصيف ذات الشعبية الكبيرة، له مسميات أخرى مثل التين الشوكي. يتميز بمذاقه المميز ✨",
  },
  {
    id: 16,
    name: "آجار البمبر (امبو)",
    nameEn: "Bamber Pickle",
    price: 55,
    discountedPrice: 49,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "500 جم",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Bamber-Pickle.jpeg",
    description: "نكهة أصيلة ومتفردة.. مثالي مع الأكلات الشعبية 😉✨",
  },
  {
    id: 17,
    name: "لوز مقطع حامض عادي",
    nameEn: "Regular Sour Almonds",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "250 جم",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Regular-Sour-Almonds.jpeg",
    description: "غير حار",
  },
  {
    id: 18,
    name: "باقة السلة المميزة",
    nameEn: "Special Basket",
    price: 350,
    discountedPrice: 299,
    discountPercent: 15,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "متنوع",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Special-Basket.jpeg",
    description:
      "سلة الأصالة 💐 … هي أكثر من هدية، هي لحظات نعيشها مع تراثنا، وطعم ماينسى من أيام الطيبين ⌛️🎁",
  },
  {
    id: 19,
    name: "جبن بقري",
    nameEn: "Cow Cheese",
    price: 45,
    discountedPrice: 39,
    discountPercent: 13,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "500 جم",
    categorySlug: "dairy",
    image: "/products/dairy/cow-cheese.jpeg",
    description: "مصنوع من الحليب البقري الطبيعي",
  },
  {
    id: 20,
    name: "شطة حارة",
    nameEn: "Hot Chili Sauce",
    price: 18,
    discountedPrice: 15,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "250 مل",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Hot-Chili-Sauce.jpeg",
    description:
      "أضف النكهة القوية واللمسة النارية لأطباقك مع صلصة الشطة الحارة",
  },
  {
    id: 21,
    name: "صوص همبا سبيشال",
    nameEn: "Himba Special Sauce",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "250 مل",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Himba-Special-Sauce.jpeg",
    description: "مزيج لذيذ يجمع بين حلاوة المانجو ولمسة من التوابل الخاصة",
  },
  {
    id: 22,
    name: "صوص همبا عادي",
    nameEn: "Himba Regular Sauce",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "250 مل",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Himba-Regular-Sauce.jpeg",
    description:
      "بلونه الأصفر الذهبي وقوامه الناعم، يجمع بين حلاوة المانجو الطبيعية ولمسة خفيفة من الحموضة",
  },
  {
    id: 23,
    name: "آجار اللوز سبيشال (حجم صغير)",
    nameEn: "Almond Pickle Special (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "200 جم",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Almond-Pickle-Special-(Small).jpeg",
    description:
      "هذا الآجار المميز الذي لا يمكن تفويته .. مذاق اللوز الاصلي مع البهارات",
  },
  {
    id: 24,
    name: "آجار همبا سبيشال (حجم صغير)",
    nameEn: "Himba Pickle Special (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "200 جم",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Himba-Special-Pickle-Small.jpeg",
    description: "ننتقي أجود أنواع الهمبا لنصنع لكم هذا الآجار المميز",
  },
  {
    id: 25,
    name: "آجار همبا عادي (حجم صغير)",
    nameEn: "Himba Pickle Regular (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "200 جم",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Himba-Regular-Pickle-Small.jpeg",
    description:
      "مخلل المانجو التقليدي الذي يأسر الحواس ويضفي لمسة خاصة على موائدكم",
  },
  {
    id: 26,
    name: "آجار ليمون (حجم صغير)",
    nameEn: "Lemon Pickle (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "200 جم",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Lemon-Pickle-(small).jpeg",
    description:
      "أضف الحموضة المنعشة لأطباقك مع آجار الليمون ذو النكهة الخلابة",
  },
  {
    id: 27,
    name: "آجار همبا حامض حلو (حجم صغير)",
    nameEn: "Himba Sour-Sweet Pickle (Small)",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "200 جم",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Himba-Sour-Sweet-Pickle (Small).jpeg",
    description:
      "استمتع بتجربة فريدة مع الآجار الذي يجمع بين الحموضة المنعشة والحلاوة الخفيفة",
  },
  {
    id: 28,
    name: "بوكس الحيب",
    nameEn: "Haib Box",
    price: 140,
    discountedPrice: 125,
    discountPercent: 11,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "متنوع",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Haib-Box.jpeg",
    description:
      "قلب النخلة 🤍🌴 ويسمى الجمار أو الجذبة في دول أخرى.. فاكهة شتوية ذات قيمة غذائية عالية جدًا وطعم لذيذ وحلو . . بالمختصر شيء فاخر 👌🏽",
  },
  {
    id: 29,
    name: "ذرة راس الخيمة الحلوة",
    nameEn: "Sweet RAK Corn",
    price: 45,
    discountedPrice: 39,
    discountPercent: 13,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "250 جم",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Sweet-RAK-Corn.jpeg",
    description:
      "من خير بلادنا 🌽 يحبها الصغير و الكبير 🥰 لذيذة و فوائدها عظيمة 😍",
  },
  {
    id: 30,
    name: "مربى توت (غرشة صغيرة)",
    nameEn: "Small Mulberry Jam",
    price: 35,
    discountedPrice: 29,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "200 جم",
    categorySlug: "juices",
    image: "/products/seasonal-fruits/Small-Mulberry-Jam.jpeg",
    description: "مربى توت طبيعي بطعم غني ولذيذ 😋 مثالي للفطور والحلويات 👌🏽✨",
  },
  {
    id: 31,
    name: "عصير توت كبير (1.5 لتر)",
    nameEn: "Large Berry Juice (1.5L)",
    price: 45,
    discountedPrice: 45,
    discountPercent: 0,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1.5 لتر",
    categorySlug: "juices",
    image: "/products/juices/Berry-Juice-large.jpeg",
    description: "عصير توت طبيعي ومنعش 🍇😋 حجم عائلي وطعم يبرد القلب 👌🏽❄️✨",
  },
  {
    id: 32,
    name: "همبا حامض (حدال) 4 كيلو",
    nameEn: "Sour Mango (4kg)",
    price: 90,
    discountedPrice: 70,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "4 كيلو",
    categorySlug: "seasonal-fruits",
    image: "/products/seasonal-fruits/Sour-Mango-(4kg).jpeg",
    description:
      "المانجو أو الامبا الحامض أو الحدال، من الثمار المعروفة بطعمها الحامض 😋 تؤكل مع الليمون والملح والفلفل وتستخدم في عمل الآجار",
  },
  {
    id: 33,
    name: "خل الليمون",
    nameEn: "Lemon Vinegar",
    price: 80,
    discountedPrice: 60,
    discountPercent: 17,
    origin: "الإمارات 🇦🇪",
    originEn: "UAE 🇦🇪",
    weight: "1.5 لتر",
    categorySlug: "pickles-sauces",
    image: "/products/pickles-sauces/Lemon-Vinegar.jpeg",
    description:
      "خل ليمون طبيعي بطعم منعش 🍋 مثالي للسلطات والتتبيلات ويضيف نكهة مميزة للأطعمة 👌✨",
  },
];

// ** Helper Functions
export function getProductsByCategorySlug(slug: string) {
  return products.filter((p) => p.categorySlug === slug);
}
export function getCategoryBySlug(slug: string) {
  return categories.find((cat) => cat.slug === slug);
}
